modLoader="javafml"
loaderVersion="[47,)"
license="CC-BY-NC 4.0"
issueTrackerURL="https://github.com/cocona20xx/no-rocket-boosting-backport/issues"
[[mods]]
modId="no_rocket_boosting"
version="1.1-backport"
displayName="No Rocket Boosting"
logoFile="assets/eg_no_rocket_boosting.png"
authors="rin (backport), enchanted games (original)"

description='''
A mod that aims to balance elytra by removing rocket boosting and adding punch bow boosting back into the game.
Includes two gamerules, 'enableElytraRocketBoosting' and 'enablePunchBowBoosting' which enable or disable firework/punch bow boosting respectively. When either of these are set to false, the vanilla behaviour is used.
'''
[[dependencies.no_rocket_boosting]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.no_rocket_boosting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
